# Default values for akeyless-services.

replicaCount: 2

image:
  repository: akeyless/base
  pullPolicy: IfNotPresent
  tag: latest

containerName: "api-gateway"

service:
  type: LoadBalancer
  portWebUi: 18888  
  portConfigureApp: 8000
  portCurlProxy: 8080
  portHvp: 8200

# Akeyless requires data persistence to be shared within all pods in the cluster
# Currently only ReadWriteMany is supported
# accessMode: ReadWriteMany
# Change the below values according to your environment except for the hostPath values
persistence:
  volumes:
    - name: akeyless-conf
      storageClassName: efs-sc
      storageClassDriver: efs.csi.aws.com
      size: 2Gi
      hostPath: /var/akeyless
      fsId: "fs-123abc45"
    - name: akeyless-profiles
      storageClassName: efs-sc
      storageClassDriver: efs.csi.aws.com
      size: 2Gi
      hostPath: /root/.akeyless
      fsId: "fs-678def90"