apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akeyless-services.fullname" . }}
  labels:
    {{- include "akeyless-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "akeyless-services.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "akeyless-services.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: akeyless-conf
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "akeyless-services.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 18888
              name: web-ui
            - containerPort: 8000
              name: configure-app
            - containerPort: 8200
              name: hpv
            - containerPort: 8080
              name: curl-proxy
          volumeMounts:
          - mountPath: /var/akeyless/conf
            name: akeyless-conf

              # - name: http
            #   containerPort: 80
            #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
