{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "akeyless-services.fullname" . }}-akeyless-services
  labels:
    app: {{ template "akeyless-services.fullname" . }}
    chart: {{ template "akeyless-services.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.persistence.hostPath }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "akeyless-services.persistence.storageClass" . }}
{{- end -}}