{{- range .Values.persistence.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name | title | lower }}
  labels:
    app: {{ $.Values.containerName }}
    chart: {{ $.Chart.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ required "A valid .Values.service.storageClassName entry required!" .storageClassName }}
  resources:
    requests:
      storage: {{ required "A valid .Values.service.size entry required!" .size }}
{{- end }}