---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeyless-services.fullname" . }}
  labels:
    {{- include "akeyless-services.labels" . | nindent 4 }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ required "A valid .Values.service.type entry required!" .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "akeyless-services.selectorLabels" . | nindent 4 }}