apiVersion: v1
kind: Service
metadata:
  name: {{ include "akeyless-services.fullname" . }}
  labels:
    {{- include "akeyless-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portWebUi }}
      targetPort: web-ui
      protocol: TCP
      name: web-ui
    - port: {{ .Values.service.portConfigureApp}}
      targetPort: configure-app
      protocol: TCP
      name: configure-app
    - port: {{ .Values.service.portCurlProxy }}
      targetPort: curl-proxy
      protocol: TCP
      name: curl-proxy
    - port: {{ .Values.service.portHvp }}
      targetPort: hpv
      protocol: TCP
      name: hpv
  selector:
    {{- include "akeyless-services.selectorLabels" . | nindent 4 }}
