# Default values for akeyless-ssh-bastion.

replicaCount: 1


# Akeyless requires data persistence to be shared within all pods in the cluster
# Currently only ReadWriteMany is supported
# accessMode: ReadWriteMany
# Change the below values according to your environment except for the hostPath values
persistence:
#  volumes: {}
  volumes:
    - name: akeyless-data
      storageClassName: efs-ssh-bastion-sc
      storageClassDriver: efs.csi.aws.com
      size: 2Gi
      mountPath: /var/run/requests
#      fsId: "fs-123abc45"

resources:
   limits:
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

HPA:
  # Set the below to false in case you do not want to add Horizontal Pod AutoScaling to the StatefulSet (not recommended)
  enabled: true
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

config:
  CAPublicKey:

  sessionTermination:
    enabled: false
    apiURL: ""
    apiToken: ""

  ## SSH log forwarding enables forwarding of the recordings of SSH sessions to customer log repository.
  ## Ref: https://docs.akeyless.io/docs/ssh-log-forwarding
  ##
  logForwording:
    enabled: false
    # Splunk example
    settings: |